version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        ports:
            - 443:443
            - 80:80
        healthcheck:
            test: service nginx status || exit 1
            interval: 10s
            timeout: 10s
            retries: 3
        restart: unless-stopped
        volumes:
            - "/etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro"
            - "/etc/letsencrypt/live/harvester.maridata.dev.52north.org/fullchain.pem:/etc/letsencrypt/live/harvester.maridata.dev.52north.org/fullchain.pem:ro"
            - "/etc/letsencrypt/live/harvester.maridata.dev.52north.org/privkey.pem:/etc/letsencrypt/live/harvester.maridata.dev.52north.org/privkey.pem:ro"
            - "mari-data-harvester_data:/www/data/:ro"

    ed2:
        build:
            context: .
            dockerfile: Dockerfile.EnvDataServer
        restart: unless-stopped
        volumes:
            - ".env.secret:/mari-data/EnvironmentalData/.env.secret:ro"

volumes:
    mari-data-harvester_data:
        external: true
