version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        ports:
            - 8000:80
        healthcheck:
            test: service nginx status || exit 1
            interval: 10s
            timeout: 10s
            retries: 3
        restart: unless-stopped
        volumes:
            - "mari-data-harvester_data:/www/data/:ro"

    api:
        build:
            context: .
            dockerfile: Dockerfile.EnvDataServer
        environment:
            - BASE_URL=http://localhost:8000/
        restart: unless-stopped
        volumes:
            - ".env.secret:/mari-data/EnvironmentalData/.env.secret:ro"

volumes:
    mari-data-harvester_data:
        external: true
