version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s %(levelname)s [%(process)d:%(processName)s %(name)s.%(funcName)s():%(lineno)d] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

#  file:
#    class: logging.handlers.RotatingFileHandler
#    formatter: standard
#    filename: /tmp/file.log
#    maxBytes: 10485760
#    backupCount: 20
#    encoding: utf8

root:
  level: INFO
  handlers: [console]
  propagate: true

loggers:
  main:
    level: DEBUG
    handlers: [console]
    propagate: false
  env_data_validator:
    level: DEBUG
    handlers: [console]
    propagate: false
  app:
    level: DEBUG
    handlers: [console]
    propagate: false
  ais:
    level: DEBUG
    handlers: [console]
    propagate: false
  config:
    level: DEBUG
    handlers: [console]
    propagate: false
  weather:
    level: DEBUG
    handlers: [console]
    propagate: false
