################################################################################
#                                                                              #
#   Copyright (C) 2021-2021 52°North Initiative for Geospatial Open Source     #
#   Software GmbH                                                              #
#                                                                              #
#   TO BE DEFINED LICENSE                                                      #
#                                                                              #
################################################################################
FROM nginx:mainline

LABEL maintainer="Eike Hinderk Jürrens <e.h.juerrens@52north.org>" \
      org.label-schema.schema-version="1.0" \
      org.label-schema.name="TBD" \
      org.label-schema.description="TBD" \
      org.label-schema.license="TBD" \
      org.label-schema.url="https://52north.orgTBD/" \
      org.label-schema.vendor="52°North GmbH" \
      org.label-schema.vcs-url="https://github.com/52north/TBD.git" \
      org.label-schema.version="x.y.z"

COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 443
EXPOSE 80
